### ISSUE TITLE
Plugin injection is very slow

### ISSUE THREAD

**Issue by owopeachy** [rankynbass/unofficial-wine-xiv-git#10]
E.g. the game hangs for about a minute just from 1 plugin update. 
 I downloaded and compiled the latest release as is on Arch and though it works fine so far plugins do take a while to finish loading/being enabled. Is this normal or are there some things I can try?

**Comment by rankynbass** [comment]
Plugin injection is just slow; I've tested vanilla wine, wine staging, valve wine, all patched and unpatched, and it all takes between 14 and 20 seconds from full-screen black window to the square logo. Without dalamud it generally around 10 seconds. So dalamud seems to add 4-10 seconds to inject on my machine, and I don't that many plugins. I know penumbra can take ages if you have enough mods.

**Comment by owopeachy** [comment]
Well, it works at least I can get used to it, thanks
