### ISSUE TITLE
wine-ntsync hangs with new ntsync5 v4

### ISSUE THREAD

**Issue by kakonema** [rankynbass/unofficial-wine-xiv-git#3]
As the title says, wine hangs indefinitely and never launches with new ntsync version (on arch). According to this post from AUR ntsync-dkms package maintainer https://github.com/Frogging-Family/wine-tkg-git/issues/936#issuecomment-2105899240 wine needs to be rebuilt against new ntsync to be able to work.

**Comment by xyphon010** [comment]
Trying the unofficial-wine-xiv-staging-ntsync-9.8 again.  Took 8 minutes to go from "ensuring compatibility tool" to "Starting game".  I switched over to CachyOS which is supposed to have the NTSYNC patches in its kernels.  Turning Dalamud off did not make a difference.

**Comment by kakonema** [comment]
fixed with wine 9.9
