### ISSUE TITLE
32 bit games not working on valveBE

### ISSUE THREAD

**Issue by klark231** [rankynbass/unofficial-wine-xiv-git#8]

**Comment by rankynbass** [comment]
I switched to using wow64-enabled builds as of 9-07. It's possible some 32-bit games and programs will not work with this 32-on-64-bit emulation. These builds are specifically for XIVLauncher.Core and Final Fantasy XIV, for which they work just fine. That said, I'll consider reverting for 9-10.

For now, you can either build it yourself by cloning the xiv-proton branch and editing the `wine-tkg-git/wine-tkg-profiles/wine-tkg-valve-exp-bleeding.cfg` file, or use ValveBE 9-06.

**Comment by rankynbass** [comment]
Closing this because I basically can't get 32-bit wine to build any more. So I will *not* be reverting this, and will continue to use wow64 builds.
